ConsumerEdition/Bubblegum-96/Downloads/Ubuntu-Core.md

Change the format and update a new link for Chinese users.

Update from uCRobotics

---

ConsumerEdition/DockerCE.md

Fixed broken link to RPB 16.03 - seems it moved to make way for 16.06.

Fixed broken link

---

ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/LinuxFastboot.md
ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/WindowsFastboot.md
ConsumerEdition/MediaTekX20/Installation/BoardRecovery.md

the PGPT is not provided and cannot be generated from source or
binary distributed by Archermind/Mediatek

remove gpt lines

---

ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/LinuxFastboot.md
ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/WindowsFastboot.md
ConsumerEdition/MediaTekX20/Installation/BoardRecovery.md

Reverts 96boards/documentation#35

Revert "remove gpt lines"

---

ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/LinuxFastboot.md
ConsumerEdition/MediaTekX20/Downloads/ThirdParty/AOSP/WindowsFastboot.md
ConsumerEdition/MediaTekX20/Installation/BoardRecovery.md

add more information on where to get image files, and how
to build image files from source code

more information on getting and build image files

---

IoTEdition/Carbon/Installation/LinuxUART.md
IoTEdition/Carbon/Installation/README.md

Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

Carbon: add instructions for flashing over USB-UART

---

ConsumerEdition/DragonBoard-410c/AdditionalDocs/README.md

Please add to Additional Documents under Application Notes

Added Clock Plan for APQ8016E app note

---

ConsumerEdition/DragonBoard-410c/Downloads/Android.md

Prevent page from getting outdated.
Signed-off-by: Victor Chong <victor.chong@linaro.org>

db410c: Android: Update static links with dynamic ones

---

ConsumerEdition/DragonBoard-410c/Guides/EnableSPIEthernetController.md

Signed-off-by: Victor Chong <victor.chong@linaro.org>

db410c: Add EnableSPIEthernetController.md

---

ConsumerEdition/DragonBoard-410c/Installation/LinuxSD.md

I flashed today and It contains license.txt
http://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Installation/LinuxSD.md/

Minor changes about Installation Step 4

---

IoTEdition/Carbon/Building/LinuxBuild/BuildDisco.md
IoTEdition/Carbon/Building/LinuxBuild/BuildShell.md

This was brought up on the forums and getting this wrong really gets users stuck!

Update carbon/zephyr build docs

---

IoTEdition/nitrogen/build/LinuxBuild/BuildDisco.md
IoTEdition/nitrogen/build/LinuxBuild/BuildShell.md

Fixed build sections to work with Nitrogen

---

ConsumerEdition/DragonBoard-410c/Guides/CameraModule.md

Signed-off-by: Todor Tomov <todor.tomov@linaro.org>

DB410c: Camera: Fix media pipeline for pix inteface

---

ConsumerEdition/DragonBoard-410c/Installation/README.md

Fixed typo in installation readme.md

---

ConsumerEdition/MediaTekX20/AdditionalDocs/README.md

Added broken image fix

---

mezzanine/README.md

Fixed relative link for stm32

---

ConsumerEdition/DragonBoard-410c/BuildSource/open_embedded.md
ConsumerEdition/DragonBoard-410c/Guides/README.md

OpenEmbedded doc and guides change for DB410c 

---

ConsumerEdition/B2260/GettingStarted/README.md
ConsumerEdition/B2260/HardwareDocs/HardwareUserManual.md
ConsumerEdition/DragonBoard-410c/README.md
ConsumerEdition/MediaTekX20/GettingStarted/README.md
ConsumerEdition/MediaTekX20Pro/GettingStarted/README.md
ConsumerEdition/MediaTekX20Pro/HardwareDocs/README.md
ConsumerEdition/MediaTekX20Pro/README.md
ConsumerEdition/guides/docker_ce.md
ConsumerEdition/guides/wifi_commandline.md
EnterpriseEdition/Cello/README.md
IoTEdition/nitrogen/hardware-docs/hardware-user-manual.md
IoTEdition/orangepi-i96/README.md
IoTEdition/orangepi-i96/getting-started/README.md
IoTEdition/orangepi-i96/support/README.md

Updated broken links

---

ConsumerEdition/B2260/GettingStarted/README.md
ConsumerEdition/B2260/HardwareDocs/HardwareUserManual.md
ConsumerEdition/B2260/README.md
ConsumerEdition/Bubblegum-96/Downloads/Ubuntu-Core.md
ConsumerEdition/Bubblegum-96/README.md
ConsumerEdition/HiKey/Installation/BoardRecovery.md
ConsumerEdition/HiKey/Installation/LinuxFactoryImage.md
ConsumerEdition/HiKey/README.md
ConsumerEdition/HiKey960/Installation/LinuxFastboot.md
ConsumerEdition/guides/mraa.md
ConsumerEdition/guides/tensorflow-installation.md
ConsumerEdition/guides/zram_swapspace.md

Documentation fixes - broken links/permalinks

---

ConsumerEdition/guides/README.md
ConsumerEdition/guides/mraa/README.md
ConsumerEdition/guides/mraa/gpio/mraa_gpio.c
ConsumerEdition/guides/mraa/gpio/mraa_gpio.cpp
ConsumerEdition/guides/mraa/gpio/mraa_gpio.py
ConsumerEdition/guides/mraa/i2c/mraa_i2c.c
ConsumerEdition/guides/mraa/i2c/mraa_i2c.cpp
ConsumerEdition/guides/mraa/i2c/mraa_i2c.py
ConsumerEdition/guides/mraa/install.md
ConsumerEdition/guides/mraa/led/mraa_led.c
ConsumerEdition/guides/mraa/led/mraa_led.cpp
ConsumerEdition/guides/mraa/led/mraa_led.py
ConsumerEdition/guides/mraa/uart/mraa_uart.c
ConsumerEdition/guides/mraa/uart/mraa_uart.cpp
ConsumerEdition/guides/mraa/uart/mraa_uart.py

guides: mraa: add examples for using peripherals

---

ConsumerEdition/imx7-96/README.md
ConsumerEdition/imx7-96/build/README.md

Removed Build from Source section from imx7 96

---

ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Images_Board/README.md
ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Images_HWUserManual/README.md
ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Images_Wiki/README.md
ConsumerEdition/MediaTekX20/Downloads/ThirdParty/README.md
ConsumerEdition/MediaTekX20Pro/Downloads/ThirdParty/README.md
ConsumerEdition/guides/mraa/README.md
ConsumerEdition/guides/mraa/gpio/README.md
ConsumerEdition/guides/mraa/i2c/README.md
ConsumerEdition/guides/mraa/led/README.md
ConsumerEdition/guides/mraa/uart/README.md

Updates to the 96boards Documentation to fix newly found 404's 

---

ConsumerEdition/DragonBoard-410c/AdditionalDocs/README.md
ConsumerEdition/MediaTekX20/Downloads/ThirdParty/README.md
ConsumerEdition/MediaTekX20Pro/Downloads/ThirdParty/README.md
ConsumerEdition/guides/mraa/i2c/README.md
ConsumerEdition/imx7-96/README.md
ConsumerEdition/imx7-96/downloads/README.md
ConsumerEdition/imx7-96/getting-started/README.md

404 fixes for documentation

---

ConsumerEdition/imx7-96/README.md
ConsumerEdition/imx7-96/support/README.md
mezzanine/neonkey/guides/README.md

Fixes for 404's found in documentation.
@shovanuk

Updates to documentation

---

ConsumerEdition/guides/mraa/README.md
ConsumerEdition/guides/mraa/gpio/README.md
ConsumerEdition/guides/mraa/i2c/README.md
ConsumerEdition/guides/mraa/led/README.md
ConsumerEdition/guides/mraa/uart/README.md

guides: mraa: Add README for examples

---

ConsumerEdition/guides/open_embedded.md

guides: OE: Update instruction for adding sources

---

ConsumerEdition/guides/compare_96boards_ce.md

remove write ups for each board

---

ConsumerEdition/guides/compare_96boards_ce.md

add div tags

---

ConsumerEdition/guides/compare_96boards_ce.md

close all <b> tags

---

ConsumerEdition/guides/compare_96boards_ce.md

A Markdown version of the table which renders correctly.
@sdrobertw @ric96

Working Markdown Version of Compare96 Table

---

ConsumerEdition/DragonBoard-410c/Guides/AOSP.md

- Updated the documentation to use kernel from @robherring 's branch qcom-4.14
- Updated flashing and building instruction with regards for the same
- Other misc changes
Tagging for review
@ndechesne

Dragonboard 410c AOSP Documentation updated

---

ConsumerEdition/DragonBoard-410c/Guides/AOSP.md

since we are using lunch target linaro_arm64-userdebug
Tagging for Review: @ndechesne

correct paths for output directory

---

ConsumerEdition/guides/aosp-index.md

A guide that consolidates links to individual build guides
and provides generic Environment Setup Instructions
Tagging for review:
@sdrobertw

guide: aosp documentation index and setup guide

---

ConsumerEdition/DragonBoard-410c/Guides/bootable-sd-card.md

Added instructions to boot Debian from sdcard.
Tagging for review:
@ndechesne

db410c: Debian SD Boot Instructions

---

ConsumerEdition/DragonBoard-410c/Guides/multi-usb-camera.md

a guide to use multiple usb cameras from a single usb hub.

guide: multiple usb camera

---

ConsumerEdition/DragonBoard-410c/Guides/multi-usb-camera.md

CE/DB410c/guides: added update/upgrade instructions to ToC

---

ConsumerEdition/guides/multi-usb-camera.md

- moved under ce/guides
- removed footnotes
- added link to mitigation for, the webcam over requesting bandwidth bug
tagging for review:
@daniel-thompson

modify guide: multi usb webcam

---

ConsumerEdition/DragonBoard-410c/Guides/README.md
ConsumerEdition/guides/README.md

updated guide index for db410c and ce common guides

---

IoTEdition/nitrogen/build/LinuxBuild/BuildBlinky.md
IoTEdition/nitrogen/build/LinuxBuild/BuildShell.md

- Issue: https://github.com/96boards/documentation/issues/214
- changes samples to cmake

IE Nitrogen: change samples to cmake

---

ConsumerEdition/guides/mraa/README.md
ConsumerEdition/guides/open_embedded.md

guides: Fix broken links

---

ConsumerEdition/DragonBoard-410c/Guides/README.md
ConsumerEdition/DragonBoard-410c/Guides/USBWebcam.md

guides: db410c: Remove usb webcam guide

---

Extras/ContributionPolicy.md

Add generic instructions for submitting a PR for fixing an issue.
Fixes: #226 

contribution_policy: Add format for submitting PR

---

EnterpriseEdition/Poplar/Guides/README.md
EnterpriseEdition/Poplar/Guides/gigabit-nas.md
EnterpriseEdition/Poplar/README.md

- guides Readme.md styled same as CE Boards
- doc/poplar/readme links to guides/readme
- fixed typo in gigabit-nas.md

modified poplar guides page

---

EnterpriseEdition/Poplar/Guides/gigabit-nas.md
EnterpriseEdition/Poplar/README.md

- fix 404 error by adding permalink
- Other typo fixes 

typo fix and permalink added

---

EnterpriseEdition/Poplar/Guides/README.md
EnterpriseEdition/Poplar/Guides/gigabit-nas.md

permalink corrections for gigabit nas guide

---

ConsumerEdition/dragonboard820c/build/README.md
ConsumerEdition/dragonboard820c/build/linux-kernel.md

Add instructions for building linux kernel from source for
Dragonboard-820c

dragonboard820c: Add guide for build from source

---

mezzanine/audio-mezzanine/Guides/advanced-guides/README.md
mezzanine/audio-mezzanine/Guides/beginner-guides/README.md

Added front matter to documentation pages.

---

ConsumerEdition/dragonboard820c/getting-started/README.md
ConsumerEdition/dragonboard820c/hardware-docs/README.md

- Added content to features table
- Added images of board
- Added Starting board for first time section
- Added links for "what's next" section
- Removed various template items that are not relevant to this board
- Made some changes to HW Docs section
- Removed template items
- Added relative link to hardware user manual

ce/db820c: Adding content for getting-started sections

---

ConsumerEdition/dragonboard820c/downloads/README.md
ConsumerEdition/dragonboard820c/downloads/android.md
ConsumerEdition/dragonboard820c/downloads/debian.md
ConsumerEdition/dragonboard820c/downloads/open-embedded.md
ConsumerEdition/dragonboard820c/installation/board-recovery.md
ConsumerEdition/dragonboard820c/installation/linux-sd.md
ConsumerEdition/dragonboard820c/installation/windows-sd.md
ConsumerEdition/dragonboard820c/support/README.md

@shovanuk 
Fixed a couple of issues with the permalink structure for  DragonBoard820c.

Fixed a few more broken links with new structure for DragonBoard820c

---

ConsumerEdition/dragonboard820c/build/README.md
ConsumerEdition/dragonboard820c/build/open-embedded.md
ConsumerEdition/guides/open_embedded.md

Added Guide to flash OE from source for 820c following structure
from 410c
Added a section for 820c in CE/guides/open_embedded.md

guide: 820c: openembedded

---

enterprise/poplar/build/README.md
enterprise/poplar/getting-started/README.md

ee: poplar: permalink typo fix

---

consumer/chameleon96/support/README.md
consumer/dragonboard410c/additional-docs/README.md
consumer/dragonboard410c/guides/uboot-linux-sd.md
consumer/dragonboard820c/downloads/android.md
consumer/dragonboard820c/downloads/debian.md
consumer/dragonboard820c/downloads/open-embedded.md
consumer/dragonboard820c/support/README.md
consumer/guides/aosp-index.md
consumer/guides/open_embedded.md
consumer/hikey/build/README.md
consumer/hikey/build/open-embedded.md
consumer/hikey/downloads/aosp.md
consumer/hikey/hardware-docs/README.md
consumer/hikey/installation/board-recovery.md
consumer/hikey/installation/linux-factory-image.md
consumer/hikey/installation/linux-fastboot.md
consumer/mediatekx20/downloads/third-party/README.md
consumer/mediatekx20/downloads/third-party/aosp/README.md
consumer/mediatekx20/downloads/third-party/aosp/linux-fastboot.md
consumer/mediatekx20/downloads/third-party/aosp/windows-fastboot.md
consumer/mediatekx20pro/downloads/third-party/README.md
consumer/mediatekx20pro/downloads/third-party/aosp/README.md
consumer/mediatekx20pro/downloads/third-party/aosp/linux-fastboot.md
consumer/mediatekx20pro/downloads/third-party/aosp/windows-fastboot.md
enterprise/poplar/additional-docs/README.md
iot/bpai96/getting-started/README.md
iot/carbon/additional-docs/README.md

broken link fixes

---

consumer/chameleon96/README.md
consumer/chameleon96/getting-started/README.md
consumer/dragonboard820c/README.md
consumer/dragonboard820c/downloads/android.md
consumer/dragonboard820c/downloads/debian.md
consumer/dragonboard820c/downloads/open-embedded.md
consumer/dragonboard820c/getting-started/README.md
consumer/dragonboard820c/support/README.md
iot/bpai96/README.md

removed non existent links

---

consumer/dragonboard410c/guides/camera-module.md

Signed-off-by: Todor Tomov <todor.tomov@linaro.org>

DB410c: Update camera doc for release 18.01

---

consumer/hikey/installation/README.md
consumer/hikey/installation/board-recovery.md
consumer/hikey/installation/linux-fastboot.md
consumer/hikey/installation/linux-sd-boot.md

- changed links for uefi, system and boot images to newer ones
- added instruction fo boot from sdcard
- modified linux-fastboot instruction for newer builds

hikey: debian sd and emmc boot instruction updated

---

consumer/guides/docker_ce.md

update docker guide to use new package name

---

consumer/dragonboard820c/downloads/debian.md
consumer/dragonboard820c/downloads/open-embedded.md
consumer/dragonboard820c/installation/README.md
consumer/dragonboard820c/installation/board-recovery.md
consumer/dragonboard820c/installation/linux-fastboot.md
consumer/dragonboard820c/installation/linux-sd.md

- Finished debian.md downloads page
- Finished openembedded.md downloads page
- Finished Installation landing page
- Finished linux-sd.md installation instruction page
- Finished linux-fastboot.md installation instruction page
- Multiple format fix commits

consumer/db820c: Multiple fixes and cleanup for downloads and installation sections

---

consumer/imx7-96/getting-started/README.md
consumer/imx7-96/guides/README.md
consumer/imx7-96/installation/board-recovery.md

- Small fixes to some i.mx7-96 content
Signed-off-by: Robert Wolff <robert.wolff@linaro.org

consumer: Small fixes to a variety of consumer board docs

---

iot/carbon/hardware-docs/README.md

carbon: remove duplicate redirect_from entries

---

iot/carbon/build/linux/build-disco.md
iot/carbon/build/linux/build-shell.md

iot: carbon: updated build instruction

---

consumer/hikey/downloads/debian.md

ce: hikey: debian download links updated

---

consumer/dragonboard820c/additional-docs/README.md
consumer/dragonboard820c/build/open-embedded.md
consumer/dragonboard820c/getting-started/README.md
consumer/dragonboard820c/installation/README.md

Thanks to @domi on the forum for reporting these.

dragonboard820c: Remove more references to Android images

---

enterprise/developerbox/README.md
enterprise/developerbox/additional-docs/README.md
enterprise/developerbox/build/README.md
enterprise/developerbox/downloads/README.md
enterprise/developerbox/downloads/debian.md
enterprise/developerbox/downloads/edk2.md
enterprise/developerbox/getting-started/README.md
enterprise/developerbox/guides/README.md
enterprise/developerbox/hardware-docs/README.md
enterprise/developerbox/installation/README.md
enterprise/developerbox/installation/board-recovery.md
enterprise/developerbox/installation/linux-usb.md
enterprise/developerbox/support/README.md

This is the first of the work needed to drag documentation out of the wiki and into real documentation.

Developerbox dewiki

---

consumer/bubblegum-96/downloads/debian.md
consumer/bubblegum-96/downloads/ubuntu-core.md
consumer/dragonboard410c/downloads/android.md
consumer/dragonboard410c/downloads/debian.md
consumer/dragonboard410c/downloads/open-embedded.md
consumer/dragonboard410c/guides/bootable-sd-card.md
consumer/dragonboard410c/guides/dt-overlays.md
consumer/dragonboard410c/guides/enable-dmic.md
consumer/dragonboard410c/guides/enable-spi.md
consumer/dragonboard410c/guides/force-display-res.md
consumer/dragonboard410c/guides/uboot-linux-sd.md
consumer/hikey/build/open-embedded.md
consumer/hikey/downloads/debian.md
consumer/mediatekx20/downloads/third-party/aosp/linux-fastboot.md
consumer/mediatekx20/downloads/third-party/aosp/windows-fastboot.md
consumer/mediatekx20/installation/board-recovery.md
consumer/mediatekx20pro/downloads/third-party/aosp/linux-fastboot.md
consumer/mediatekx20pro/downloads/third-party/aosp/windows-fastboot.md
consumer/mediatekx20pro/installation/board-recovery.md
iot/carbon/downloads/zephyr.md
iot/nitrogen/downloads/zephyr.md

Migrate links from builds.96boards.org to releases.linaro.org

---

consumer/dragonboard410c/downloads/open-embedded.md

consumer/db410c/downloads/oe: Link fixes

---

consumer/dragonboard820c/installation/board-recovery.md

Also includes instructions to (re)provision UFS disk. And while at it, fixed a couple of typos.

Add instruction to flash/recover with QDL tool

---

consumer/dragonboard820c/hardware-docs/README.md

consumer/db820c/hardware-docs: Added view and download links

---

consumer/b2260/README.md
consumer/dragonboard410c/downloads/android.md
consumer/hikey/downloads/aosp.md
consumer/hikey/downloads/open-embedded.md

A few fixes for the broken links stopping the themed site from building.

Fixed broken build links in documentation

---

consumer/hikey/downloads/open-embedded.md

Two remaining broken links fixed.

Remaining broken 96Boards build links fixed

---

consumer/dragonboard820c/getting-started/README.md

db820c: Fix i.MX7 copy 'n paste error

---

consumer/hikey/downloads/open-embedded.md

@Mani-Sadhasivam  suggested to use these instead.
@daniel-thompson

Added more generic URL's for builds

---

consumer/ultra96/hardware-docs/README.md

consumer/ultra96: Fixed relative links in hardware-docs section

---

consumer/ultra96/installation/README.md

consumer/ultra96: link fix

---

enterprise/developerbox/hardware-docs/README.md

developerbox: Add link to the assembly manual

---

consumer/dragonboard410c/guides/aosp.md

db410c: aosp guide update with recent build and flash instructions

---

consumer/dragonboard820c/installation/build-linux-host.md
consumer/dragonboard820c/installation/linux-fastboot.md

Completed the installation instructions for novices with the **Build Linux Host Computer** guide.
Also **simplified/automated** getting the **latest build**.

Build linux host

---

consumer/dragonboard820c/hardware-docs/README.md

db820c: hardware-docs: Fix broken link for user guide

---

consumer/ultra96/downloads/README.md

ultra96: added OpenSUSE as third party OS

---

consumer/dragonboard410c/build/kernel.md

* Use $ARCH instead of hardcoding
* switch to compressed kernel image
* fixup default defconfig to use

Various improvements

---

enterprise/developerbox/guides/install-over-http.md

devbox: fix install over http guide link issue

---

consumer/b2260/README.md
consumer/bubblegum-96/README.md
consumer/dragonboard410c/README.md
consumer/dragonboard820c/README.md
consumer/hikey960/README.md
consumer/imx7-96/README.md
consumer/rock960/README.md
enterprise/developerbox/README.md
enterprise/poplar/README.md
iot/bpai96/README.md
iot/carbon/README.md
iot/nitrogen/README.md
iot/orangepi-i96/README.md

"It would never in a million years have occured to me to look
for a board recovery guide under the heading Support!" - danielt

Update all Support pages to be Troubleshooting-and-Support

---

guides.md

guides.md contains index of available guides in the doc repo

WIP: guides indexing

---

consumer/dragonboard820c/build/linux-kernel.md

Corrected some errors and added more detailed instructions

Update 820c source build instructions

---

consumer/dragonboard820c/build/linux-kernel.md

Attempt to fix broken link in recent PR

---

consumer/dragonboard410c/guides/camera-module.md

consumer/db410c/guides: Attempt to fix broken link for website build

---

enterprise/developerbox/README.md
enterprise/developerbox/installation/README.md
enterprise/developerbox/installation/linux-usb.md
enterprise/developerbox/installation/mac-usb.md
enterprise/developerbox/installation/windows-usb.md

Another collection of changes. These are mostly focused on the final polish and on presenting ideas to the user in the correct order!

developerbox: Part the fourth

---

templates/board-template/build/README.md
templates/board-template/build/aosp.md
templates/board-template/build/debian.md
templates/board-template/build/kernel.md
templates/board-template/build/oe.md
templates/board-template/hardware-docs/hardware-user-manual.md
templates/board-template/installation/linux-sd.md
templates/board-template/installation/mac-sd.md
templates/board-template/installation/windows-sd.md

templates: make templates more generic

---

consumer/dragonboard820c/guides/README.md
consumer/dragonboard820c/guides/aosp.md

db820c: add aosp build guide

---

consumer/hikey/downloads/aosp.md
guides/README.md
guides/crosscompile/CommandLine.md
guides/crosscompile/EclipseIDE.md

link fixes

---

mezzanine/shiratech-lte/README.md

mezzanine: Added Shiratech LTE mezzanine

---

CONTRIBUTE.md

contribute: add guides section and other misc improvements

---

consumer/hikey970/ai/README.md

consumer/hikey970/ai: Added relative links to ai sections

---

consumer/hikey970/build/README.md
consumer/hikey970/downloads/README.md
consumer/hikey970/getting-started/README.md
consumer/hikey970/guides/README.md
consumer/hikey970/hardware-docs/README.md
consumer/hikey970/support/README.md

- Added relative links to hardware-docs
- Small changes to top level README.md
- Edits to getting-started and downloads sections
- Added relative links to guides section
- Almost finished with getting started section
- Finishing the table is still needed

consumer/hikey970: Several changes to populate the template

---

enterprise/developerbox/installation/README.md

Developerboxen -> Developerbox)
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

enterprise/developerbox: fix typo

---

guides/README.md

guides: format changes and additions to content

---

guides/README.md

guides: small fixes to format and links

---

guides/README.md

guides: Format changes and added content to index

---

README.md

Added a couple relative links to top markdown page

---

consumer/guides/tensorflow-installation.md

Removed link to http://www.danielslater.net/2016/03/deep-q-learning-pong-with-tensorflow.html

Removed broken link to a blog post that no longer exists

---

consumer/hikey970/README.md

Testing webhook configuration for the 96Boards.ai docs

Small change to trigger a build of the 96Boards.ai documentation.

---

enterprise/developerbox/hardware-docs/README.md

This may eventually have to move to separate more comprehensive section... but for now lets capture it here.

developerbox: hardware-docs: Include the list of verified RAM

---

consumer/ultra96/README.md
consumer/ultra96/downloads/linux.md

ultra96: Adding content to landing page and downloads section

---

CONTRIBUTE.md

contrib: Updated to add video tutorials

---

consumer/hikey970/guides/README.md
consumer/rock960/ai/README.md
consumer/ultra96/ai/README.md
consumer/ultra96/hardware-docs/hw-user-manual.md
consumer/ultra96/support/README.md

- Added AI sub folders to the boards

Updates to fix broken links when building the AI documentation

---

consumer/guides/disable_gui.md
consumer/guides/docker_ce.md
consumer/guides/sd_swapspace.md
consumer/guides/wifi_commandline.md
consumer/guides/zram_swapspace.md
guides/README.md
mezzanine/neonkey/README.md

- added links to videos
- added link to pinout website
- fix the link to neonkey aosp build guide

Misc Guides Improvements

---

enterprise/developerbox/downloads/README.md
enterprise/developerbox/installation/debian.md
enterprise/developerbox/installation/ubuntu.md
enterprise/developerbox/support/README.md
enterprise/developerbox/support/known-issues.md

Hi Folks
This PR is the list of known issues for Developerbox (with workarounds) and a cheat sheet style list of quirks to assist the user install their choice of distro. Currently there are only cheat sheets for Ubuntu and Debian but I hope to follow up soon with ones for Fedora and CentOS.
Daniel.

Developerbox: Known issues and distro HOWTO

---

consumer/hikey/downloads/README.md
iot/4iot/support/README.md

Singed-off-by: Robert Wolff <robert.wolff@linaro.org>

Attempt to fix broken links in documentation

---

mezzanine/stm32/guides/advanced-guides/README.md
mezzanine/stm32/guides/advanced-guides/stand-alone.md
mezzanine/stm32/guides/beginner-guides/README.md

fix broken links

---

mezzanine/stm32/guides/beginner-guides/getting-started.md

stm32: fix images

---

mezzanine/aerocore2/README.md
mezzanine/d3camera/README.md
mezzanine/linkspritesensorkit/README.md
mezzanine/mipiadapter/README.md
mezzanine/neonkey/README.md
mezzanine/secure96/README.md
mezzanine/stm32/README.md
mezzanine/stm32/guides/beginner-guides/arm-mbed.md
mezzanine/uartserial/README.md

typo and spell check

---

consumer/hikey970/downloads/README.md
consumer/hikey970/downloads/aosp.md
consumer/hikey970/installation/README.md
consumer/hikey970/installation/board-recovery.md
consumer/hikey970/installation/linux-fastboot.md

Add HiKey970 download and installation guide for AOSP/

hikey970: Add AOSP download and installation guide

---

enterprise/developerbox/downloads/README.md

developerbox: downloads: Fix RHEL download link

---

iot/bpai96/getting-started/README.md
iot/bpai96/installation/README.md
iot/bpai96/installation/windows.md

installation instructions are still very sparse

bpai: attempt to fix formatting

---

consumer/hikey970/build/README.md
consumer/hikey970/build/aosp.md
consumer/hikey970/build/linux-kernel.md

hikey970: build doc: aosp and linux

---

consumer/b2260/downloads/debian.md

consumer/b2260/downloads: Fixed debian image link

---

mezzanine/stm32/README.md
mezzanine/stm32/files/README.md

stm32-mezz: added hw manual doc

---

enterprise/developerbox/getting-started/README.md
enterprise/developerbox/hardware-docs/README.md

enterprise/developerbox: Attempt to fix broken link

---

iot/bpi96/README.md
iot/bpi96/additional-docs/README.md
iot/bpi96/build/README.md
iot/bpi96/downloads/README.md
iot/bpi96/getting-started/README.md
iot/bpi96/guides/README.md
iot/bpi96/hardware-docs/README.md
iot/bpi96/installation/README.md
iot/bpi96/support/README.md

bpi: fix broken links

---

iot/bpi96/README.md
iot/bpi96/additional-docs/README.md
iot/bpi96/build/README.md
iot/bpi96/downloads/README.md
iot/bpi96/getting-started/README.md
iot/bpi96/guides/README.md
iot/bpi96/hardware-docs/README.md
iot/bpi96/installation/README.md
iot/bpi96/support/README.md

bpi: broken link fix attempt

---

iot/bpi96/hardware-docs/hardware-user-manual.md

minor change to trigger builds

---

consumer/mediatekx20/additional-docs/README.md

mediatekx20: Fix duplicate link and typos

---

iot/4iot/README.md
iot/4iot/additional-docs/README.md
iot/4iot/build/README.md
iot/4iot/build/aosp.md
iot/4iot/build/debian.md
iot/4iot/build/kernel.md
iot/4iot/build/oe.md
iot/4iot/downloads/README.md
iot/4iot/downloads/debian.md
iot/4iot/getting-started/README.md
iot/4iot/guides/README.md
iot/4iot/hardware-docs/README.md
iot/4iot/installation/README.md
iot/4iot/installation/linux-sd.md
iot/4iot/installation/mac-sd.md
iot/4iot/installation/windows-sd.md
iot/4iot/support/README.md

consumer/4iot: Attempt to fix broken links

---

consumer/dragonboard820c/getting-started/README.md

As agreed in issue #316, this commit removes Features section from the board
getting started page.
Fixes: #316

db820c: Remove Features section

---

consumer/hikey970/installation/linux-fastboot.md

consumer/hikey970/installation: Attempt to fix broken link

---

mezzanine/arrow-nextbio/README.md
mezzanine/arrow-nextbio/files/README.md

mezzanine/arrow-nextbio: Attempt to fix broken links

---

mezzanine/xinabox-b901/README.md
mezzanine/xinabox-b901/files/README.md
mezzanine/xinabox-b901/guides/README.md
mezzanine/xinabox-b901/images/README.md

mezzanine: Added xinabox-b901 mezzanine folder to the lineup

---

consumer/ultra96/README.md
consumer/ultra96/build/README.md
consumer/ultra96/build/peta-linux.md

guides: ultra96: build PetaLinux

---

mezzanine/arrow-nextbio/README.md

mezzanine/arrow-nextbio: Added unlinked ToC to README.md

---

consumer/rock/rock960c/README.md
consumer/rock/rock960c/additional-docs/README.md
consumer/rock/rock960c/ai/README.md
consumer/rock/rock960c/build/README.md
consumer/rock/rock960c/build/aosp.md
consumer/rock/rock960c/downloads/README.md
consumer/rock/rock960c/downloads/debian.md
consumer/rock/rock960c/downloads/ubuntu.md
consumer/rock/rock960c/getting-started/README.md
consumer/rock/rock960c/guides/README.md
consumer/rock/rock960c/guides/serial-console.md
consumer/rock/rock960c/hardware-docs/README.md
consumer/rock/rock960c/hardware-docs/hardware-revision.md
consumer/rock/rock960c/hardware-docs/hardware-user-manual.md
consumer/rock/rock960c/installation/README.md
consumer/rock/rock960c/installation/linux-mac-rkdeveloptool.md
consumer/rock/rock960c/installation/linux-sd.md
consumer/rock/rock960c/installation/mac-sd.md
consumer/rock/rock960c/installation/windows-sd.md
consumer/rock/rock960c/support/README.md

consumer/rock/rock960c: Fixed broke links (attempt)

---

enterprise/developerbox/getting-started/README.md
enterprise/developerbox/hardware-docs/README.md

developerbox: Update assembly instruction to latest

---

consumer/hikey/hikey970/build/aosp.md
consumer/hikey/hikey970/downloads/README.md

also fixed links for aosp build doc
fixes #540

hikey970: add lemaker debian and ubuntu image links

---

consumer/hikey/hikey960/downloads/debian.md

consumer/hikey/hikey960/downloads: Attempt to fix broken links

---

consumer/hikey/hikey620/downloads/debian.md
consumer/hikey/hikey620/installation/board-recovery.md

consumer/hikey: Attempt to fix broken links for build

---

consumer/hikey/hikey620/guides/jtag/README.md

Attempt to fix broken linked

---

consumer/hikey/hikey960/installation/board-recovery.md

Add board recovery guide for HiKey960.

consumer: hikey960: Add board recovery guide

---

consumer/guides/open_embedded.md
consumer/hikey/hikey960/build/open-embedded.md

This PR adds OpenEmbedded guide for Hikey960
Fixes: #189 

Add OE guide for HiKey960

---

consumer/README.md

consumer: Small changes to top level consumer README

---

consumer/hikey/hikey970/installation/board-recovery.md

1. Add instructions for generating l-loader.bin
2. Fix boot switch position for recovery
3. Remove reference to OP-TEE

hikey970: Add instructions for generating l-loader.bin and some cleanups

---

consumer/hikey/hikey620/hardware-docs/hardware-user-manual.md

hikey: fixed broken images on hardware user manual

---

consumer/ultra96/guides/README.md
enterprise/developerbox/downloads/edk2.md

TODO: add links back when they are re-uploaded

devbox: removing links to edk2

---

consumer/dragonboard/dragonboard410c/guides/bootable-sd-card.md

db410c: sd-card boot guide: update snapshot links

---

consumer/dragonboard/dragonboard410c/guides/README.md
consumer/dragonboard/dragonboard410c/guides/terminal.md
consumer/dragonboard/dragonboard820c/installation/README.md
consumer/dragonboard/dragonboard820c/installation/linux-sd.md
consumer/hikey/hikey620/installation/linux-factory-image.md
consumer/hikey/hikey970/installation/README.md
consumer/hikey/hikey970/installation/linux-sd.md
consumer/hikey/hikey970/installation/mac-sd.md
consumer/hikey/hikey970/installation/windows-sd.md

- commented/removed "comming soon" sd card instructions for hikey970
fixes #569
- hikey fixed formatting for installation instructions
fixes #544
- Removed teminal.md, the guide for empty since it was created
fixes #505
- commented/removed sd card instructions for db410c
Not sure if db820 supports booting debian from sd yet
fixes #347

misc fixes:

---

consumer/ultra96/hardware-docs/README.md

link fixed: ultra96 product brief pdf link updated

---

consumer/hikey/hikey620/downloads/aosp.md

Temporarily removed link to fix website build

consumer/hikey/hikey620/downloads/aosp: Fix broken link

---

consumer/hikey/hikey970/installation/linux-fastboot.md

hikey970: add Lebian install instructions

---

consumer/ultra96/downloads/README.md
consumer/ultra96/guides/README.md

ultra96: added download and documentation links for pynq

---

consumer/hikey/hikey620/hardware-docs/hardware-user-manual.md

Hardware user manual images fixed

Hardware user manual images fixed

---

consumer/ultra96/guides/README.md

ultra96: link fixed for BNN Guide

---

consumer/sophon-edge/ai/README.md
consumer/sophon-edge/getting-started/README.md

consumer/sophon-edge: Small fixes, added pictures

---

consumer/sophon-edge/getting-started/README.md

consumer/sophon-edge: Small fix to getting-started section

---

consumer/README.md

consumer: Added Sophon Edge to documentation table

---

consumer/sophon-edge/getting-started/README.md
consumer/sophon-edge/guides/README.md

consumer/sophon-edge: Small fixes to a couple section

---

iot/wistrio/hardware-docs/README.md

iot/wistrio: Attempt to fix broken links

---

iot/wistrio/downloads/README.md

Populate download.md with links to IDE and
Toolchain, Driver etc.
These links are not properly setup in the
user manual pdf file.

iot: wistrio: add download links

---

iot/wistrio/support/README.md

iot/wistrio: Added link to forum in support section of doc

---

enterprise/developerbox/downloads/debian.md

enterprise/developerbox: Small change to debian download section

---

enterprise/developerbox/downloads/debian.md
enterprise/developerbox/downloads/edk2.md
enterprise/developerbox/getting-started/README.md
enterprise/developerbox/installation/README.md
enterprise/developerbox/installation/board-recovery.md
enterprise/developerbox/installation/centos.md
enterprise/developerbox/installation/debian.md
enterprise/developerbox/installation/rhel.md
enterprise/developerbox/installation/ubuntu.md

Reformatting the dev box workflow: Merging Download and Installation pages and slight changes to getting started page

Reformatting Developerbox Documentation

---

enterprise/oxalis/README.md
enterprise/oxalis/build/README.md
enterprise/oxalis/downloads/README.md
enterprise/oxalis/downloads/linux.md
enterprise/oxalis/getting-started/README.md
enterprise/oxalis/guides/README.md
enterprise/oxalis/hardware-docs/README.md
enterprise/oxalis/hardware-docs/hw-user-manual.md
enterprise/oxalis/installation/README.md
enterprise/oxalis/support/README.md

enterprise/oxalis: Attempt to fix broken website build

---

enterprise/oxalis/build/README.md
enterprise/oxalis/build/linux.md
enterprise/oxalis/downloads/linux.md
enterprise/oxalis/installation/README.md
enterprise/oxalis/installation/linux.md

- added a build guide for linux build using nxp sdk
- added linux installation guilde
- added download link for prebuilt linux image

oxalis: added build and installation guilds

---

enterprise/oxalis/installation/linux.md

Minor fixes to the Oxalis board installation doc.

oxalis: Minor fixes to the installation doc

---

consumer/hikey/contribute.md
consumer/hikey/hikey620/README.md
consumer/hikey/hikey960/README.md
consumer/hikey/hikey970/README.md

Add kernel contribution guide for making it easy for the developers who
are willing to contribute to the Linaro release kernel.
PS: ITS ticket has been submitted for creating `hikey-kernel` mailing list.

hikey: Add kernel contribution guide for all hikey family boards

---

iot/wistrio/downloads/README.md

wistrio: update sample code repo

---

consumer/guides/aosp-index.md
consumer/guides/mraa/install.md
consumer/guides/multi-usb-camera.md
consumer/guides/open_embedded.md

- AOSP Build Guide
- OE Yocto build guide
- Multiple USB Camera guide
- MRAA Build guide

guide: link videos for various guides

---

consumer/dragonboard/dragonboard820c/downloads/debian.md
consumer/dragonboard/dragonboard820c/downloads/open-embedded.md
consumer/dragonboard/dragonboard820c/installation/board-recovery.md
consumer/hikey/contribute.md
consumer/hikey/hikey960/downloads/aosp.md
consumer/rock/downloads/debian.md
consumer/rock/downloads/ubuntu.md
enterprise/cello/quickstart/README.md
iot/ivy5661/hardware-docs/README.md

Most of these links have to be refixed later.

[Refix later] Fix broken links

---

consumer/rock/rock960c/getting-started/README.md
mezzanine/shiratech-fpga/guides/fpga-getting-started.md
mezzanine/shiratech-fpga/guides/restore-factory-firmware.md

- fixed thubnail links for fpga mezzanine guides
- replaced rock960c links to rock960

link fixes:

---

mezzanine/shiratech-fpga/guides/README.md
mezzanine/shiratech-fpga/guides/i2c-shields.md

A guide to demo runign i2c shields and sensors using the fpga mezzanine.

guide: fpga-mezz: i2c shields

---

consumer/rock/build/README.md
consumer/rock/build/lakka.md

Added a guide to build LakkaTV os from source.

ce: rock960: lakka build guide

---

consumer/hikey/hikey620/guides/booting-linux-kernel-using-uboot.md

Add Booting Linux Kernel using U-Boot guide for HiKey board.

hikey: guides: Add Booting Linux Kernel using U-Boot guide

---

consumer/sophon-edge/support/README.md

product/consumer/sophon-edge/support: Added link to Bitmain Forum

---

consumer/ultra96/README.md
consumer/ultra96/kits/README.md

consumer/ultra96: Small fixes for new kits section

---

consumer/ultra96/kits/delta-camera.md

link fix for ultra96 kits

---

consumer/ultra96/support/README.md

consumer/ultra96/support: Added link to 96Boards forum page

---

consumer/ultra96/kits/delta-camera.md

kits: ultra96 delta: populated kits page for deltavision

---

mezzanine/sensors-mezzanine/README.md

sensor-mezzanine fix and test examples

---

consumer/dragonboard/dragonboard410c/guides/README.md
consumer/dragonboard/dragonboard820c/guides/README.md
consumer/dragonboard/guides/README.md
consumer/guides/aosp-index.md

Attempting to fix broken links for Dragonboard family aosp guides

Attempting to fix broken links for Dragonboard family aosp guides

---

mezzanine/shiratech-nb1/guides/README.md

mezzanine/shiratech-nb1: Attempt to fix broken links for website build

---

consumer/dragonboard/dragonboard410c/guides/README.md
consumer/dragonboard/dragonboard410c/guides/fedora.md

Following Peter Robbinson's guide:
https://nullr0ute.com/2017/11/getting-started-with-fedora-on-the-96boards-dragonboard/

db410c: guide: fedora installation

---

mezzanine/shiratech-fpga/guides/README.md
mezzanine/shiratech-fpga/guides/fpga-mezzanine-library.md

fpga-mezzi: fpga mezzanine library documentation

---

consumer/sophon-edge/guides/README.md
consumer/sophon-edge/guides/SD_Boot_Guide.md

Reformating Sophon-Edge's Useful Guide section to standard format. Also adding an SD boot guide.

Sophon Edge Useful Guides Update

---

iot/ivy5661/build/README.md
iot/ivy5661/build/linux.md
iot/ivy5661/downloads/zephyr.md
iot/ivy5661/getting-started/README.md
iot/ivy5661/hardware-docs/README.md
iot/ivy5661/installation/README.md
iot/ivy5661/installation/linux.md

iot: ivy5661: added getting started guide and fixed broken links

---

mezzanine/shiratech-fpga/guides/README.md
mezzanine/shiratech-fpga/guides/l298n.md
mezzanine/shiratech-fpga/guides/relay-shield.md

fpga-mezz: add l298n and relay shield guides

---

README.md

Removed duplicated edit on GitHub link

Removed duplicated edit on GitHub link

---

consumer/dragonboard/README.md
consumer/dragonboard/dragonboard410c/getting-started/audio-kit/README.md
consumer/dragonboard/dragonboard410c/getting-started/aws-kit/README.md
consumer/dragonboard/dragonboard410c/getting-started/basic-kit/README.md
consumer/dragonboard/dragonboard410c/hardware-docs/README.md

Remove all occurrence of Snapdragon in DB410c folder
Replace occurrence of Snapdragon with APQ8016E.

Remove all occurrence of Snapdragon

---

mezzanine/tresor/guides/README.md
mezzanine/tresor/guides/tresor-guide.md

mezzanine: tresor: Add getting started guide

---

consumer/README.md

Well... maybe it's just a copy and paste error, but it still needs to be removed.

consumer: Remove subliminal advertising

---

enterprise/developerbox/getting-started/README.md

3rd party link fix

---

mezzanine/voice-ui/README.md

Small content change for ToC

---

mezzanine/tresor/README.md

tresor mezzanine image link fixed

---

consumer/dragonboard/dragonboard410c/downloads/README.md
enterprise/README.md

- Fixed enterprise table
- fixes #716
- Fixed Win10 IoT Link for db410c
- fixes #719

documentation fixes:

---

consumer/sophon-edge/guides/README.md
consumer/sophon-edge/guides/sd_boot_guide.md

Adding Front matter to SD boot guide and renaming the file

adding front matter to SD boot guide and renaming

---

iot/ivy5661/build/linux.md

Rework IVY5661 build guide by fixing the formatting and removing the
duplicate sections.

iot: ivy5661: Rework the build guide

---

consumer/dragonboard/dragonboard410c/downloads/debian.md
consumer/dragonboard/dragonboard410c/downloads/open-embedded.md

Signed-off-by: Sahaj Sarup <sahajsarup@linaro.org>

db410c: rescue image link fix

---

mezzanine/on-camera/README.md

Small change for link fix

---

consumer/dragonboard/dragonboard845c/guides/README.md
consumer/dragonboard/dragonboard845c/guides/button-events.md
consumer/dragonboard/dragonboard845c/guides/can.md
consumer/dragonboard/dragonboard845c/guides/dmic.md
consumer/dragonboard/dragonboard845c/guides/fan-control.md
consumer/dragonboard/dragonboard845c/guides/wifi.md

Added the following basic guides:
- Button Events
- Fan Control
- WiFi
- Digital Microphone
Signed-off-by: Sahaj Sarup <sahajsarup@linaro.org>

db845c: Added basic guides

---

consumer/dragonboard/dragonboard845c/getting-started/README.md

consumer/dragonboard845c: Adjustment to kit page

---

consumer/dragonboard/dragonboard845c/downloads/README.md

consumer/dragonboard845c: Addition to Download page

---

consumer/dragonboard/dragonboard845c/installation/README.md

Small fix to Installation page title

consumer/dragonboard845c: Small fix

---

consumer/dragonboard/dragonboard845c/getting-started/README.md

Adjustment made to content of kit in getting
started section

consumer/db845c: Adustment to rb3 kit contents

---

consumer/hikey/hikey960/installation/board-recovery.md

hikey960: board recovery: Update to match latest filenames

---

consumer/rock/downloads/android.md

update new android tv download link.

Rock960: update download link for new version android tv image

---

consumer/dragonboard/dragonboard410c/guides/fedora.md

fix typo for arm-image installer media flag

---

consumer/rock/rock960c/guides/camera-setup.md

hi 
update camera interface guide for Rock960 Model C boards

rock960: update camera interface guide for Rock960 Model C

---

consumer/dragonboard/dragonboard845c/guides/README.md
consumer/dragonboard/dragonboard845c/hardware-docs/README.md

- Added link to hardware user manual
- Added link to schematics
- Added link to linux user guide

Added documentation links to guides and hardware docs sections

---

consumer/dragonboard/dragonboard845c/hardware-docs/README.md

consumer/db845c: Attempt to fix broken link

---

consumer/hikey/hikey970/downloads/aosp.md
consumer/rock/build/aosp.md

- Corrected Rock960 AOSP source code space requierment
fixes #761
- Corrected Hikey970 Android download link
fixes #759

fixes: minor doc fixes

---

consumer/avenger96/README.md
consumer/avenger96/getting-started/README.md
consumer/avenger96/installation/sd-etcher-install.md
consumer/avenger96/support/README.md

avenger96: link fixes

---

mezzanine/shiratech-fpga/guides/README.md
mezzanine/shiratech-fpga/guides/simple-spi-hats.md

shiratech-fpga: guide: simple spi hats

---

mezzanine/aiva-96/README.md

Fix broken image src

---

mezzanine/aiva-96/guides/README.md

aiva96: link to amazon sdk demo

---

consumer/rock/build/aosp.md

Rock960:update aosp build steps.

---

consumer/rock/guides/README.md
consumer/rock/guides/expand-rootfs.md

rock: guide: expand rootfs in ubuntu

---

consumer/dragonboard/dragonboard845c/installation/board-recovery.md
consumer/guides/qdl.md

consumer: db845c: document USB flashing

---

consumer/ultra96/ultra96-v2/guides/README.md

- These changed were made as a demonstration.

Added coming soon section to guides table on v2 Ultra96

---

consumer/dragonboard/dragonboard845c/downloads/README.md
consumer/dragonboard/dragonboard845c/downloads/debian.md
consumer/dragonboard/dragonboard845c/downloads/open-embedded.md
consumer/dragonboard/dragonboard845c/installation/README.md
consumer/dragonboard/dragonboard845c/installation/le.md
consumer/dragonboard/dragonboard845c/installation/linux-fastboot.md

db845c: added debian and oe download and install instructions

---

som/tb-96ai/build/android.md
som/tb-96ai/getting-started/README.md
som/tb-96ai/installation/README.md
som/tb-96ai/installation/windows.md

- Fixed typos
- Mistake name replacement
- Build command fix

som/tb-96ai: Small fixes across the doc set

---

som/tb-96aiot/build/buildroot.md
som/tb-96aiot/downloads/README.md
som/tb-96aiot/installation/README.md

- Link fixes in Download section
- Mistake name replacement
- Build command fix for Uboot and Linux kernel

som/tb-96aiot: Small fixes across the doc set

---

consumer/hikey/hikey620/downloads/aosp.md

hikey: fix aosp download link

---

consumer/rock/downloads/android.md

Rock960:update aosp download links

---

consumer/dragonboard/dragonboard845c/installation/README.md

* few typos
* fastboot is the only method to install a software

READMDE: coupe of updates

---

consumer/dragonboard/dragonboard845c/installation/board-recovery.md
consumer/guides/compare_96boards_ce.md
consumer/hikey/hikey620/installation/README.md

**Fix for the following issues:**
- https://github.com/96boards/documentation/issues/836
- https://github.com/96boards/documentation/issues/835
- https://github.com/96boards/documentation/issues/833

Fix for issues #833, #835, and #836

---

consumer/sophon-edge/getting-started/README.md

Fix to issue #635 regarding Sophon Edge compliance

---

consumer/avenger96/installation/README.md

avenger96: Remove broken boilerplate

---

consumer/avenger96/downloads/README.md
som/tb-96ai/getting-started/README.md

Documentation updates requested by Joyce Qi:
SoM AI Board Mux Switches update + Avengers96 downloads link added

SoM AI Board Mux Switches update + Avengers96 downloads link added

---

som/tb-96aiot/getting-started/README.md

Updated MUX switches descriptions for TB-96AIoT

Updated MUX switches descriptions for TB-96AIoT

---

consumer/avenger96/support/README.md

Corrected Avenger96 forum link title

Corrected Avenger96 forum link title

---

consumer/dragonboard/dragonboard845c/installation/linux-fastboot.md

The updated steps now match those in #853 
Signed-off-by: Servando German Serrano <servando.german.serrano@linaro.org>

Updated fastboot steps

---

mezzanine/3dtof/README.md
mezzanine/3dtof/guides/README.md

Also change product name to "Analog Device’s 3D Time Of Flight Mezzanine Stack"

mezzanine: 3dtof: updated guides and sdk link

---

consumer/ultra96/ultra96-v2/getting-started/README.md

Signed-off-by: Servando German Serrano <servando.german.serrano@linaro.org>

Added link to v1 instructions

---

enterprise/developerbox/build/README.md
enterprise/developerbox/installation/board-recovery.md

This pull request is adding OSS SCP-firmware build instruction for Developerbox.
Also updated flasher usage.
Signed-off-by: Masahisa Kojima masahisa.kojima@linaro.org

Add scpfirmware build

---

consumer/aiml/build/README.md
consumer/aiml/build/mainline.md
consumer/aiml/guides/README.md

Signed-off-by: Servando German Serrano <servando.german.serrano@linaro.org>

Added build instructions for mainline kernel

---

Specifications/README.md

Signed-off-by: Loic Poulain <loic.poulain@linaro.org>

Update specifications README with SOM specs

---

README.md
Specifications/README.md
consumer/README.md
consumer/dragonboard/dragonboard410c/vendor-docs/README.md
enterprise/README.md
iot/README.md
mezzanine/README.md
som/README.md

Updates to documentation for new website theme implementation

Updates to documentation for new website theme implementation

---

consumer/e850-96b/getting-started/README.md
consumer/e850-96b/installation/README.md

Change-Id: I0500c1031d6c32bc99898664aac8db5369ac22d2

ce: e850: miscellaneous fixes

---

consumer/README.md

Explicitly mention device families to simplify navigation.

consumer: mention device families

---

consumer/dragonboard/qualcomm-robotics-rb5/downloads/open-embedded.md

Simplified some of the regular expressions to make more readable while I was at it.

Fix OE broken links
