96boards/documentation

ConsumerEdition/DragonBoard-410c/Installation/MacSD.md
Includes describing the Disk Utility including a common problem of receiving the "resource busy" when trying to use the dd command.
=> Added additional details from Mac side

MezzanineProducts/README.md
SMT32 link was incorrectly pointing to the UART serial adapter
=> Fix incorrect link in README.md

ConsumerEdition/HiKey/Functionality/EarlyCon.md
Early Console (earlycon) is a useful feature for kernel
developers who have a tendency to break kernels and need console output
to debug. This provides documentation for enablement on HiKey.
=> Documentation for working with early console with HiKey

ConsumerEdition/DragonBoard-410c/Downloads/README.md
(and sort the third-party builds alphabetically)
=> DragonBoard-410c: Describe Android is a third-party build

ConsumerEdition/DragonBoard-410c/Installation/LinuxFastboot.md
In LinuxFastboot we have just a android-tools install from the source code.
My suggestion is add a distro package manager install example for this.
=> LinuxFastboot: Added android-tools install from yum package manager.

ConsumerEdition/HiKey/Downloads/AOSP.md
See https://bugs.96boards.org/show_bug.cgi?id=588
=> Switch links from (obsolete) release to (up-to-date) snapshot

ConsumerEdition/DragonBoard-410c/Guides/dt-overlays.md
Hardcoded number of cores in make command was replaced
by nproc.
=> DragonBoard-410c/Guides: Replaced hardcode by nproc.

ConsumerEdition/DragonBoard-410c/Installation/LinuxFastboot.md
I found that I needed to reboot my DB410c after flashing the boot
loader, otherwise I could not successfully flash the root file
system.
Signed-off-by: Alex Elder <elder@linaro.org>
=> DB-410c: LinuxFastboot.md: reboot after flashing bootloader

ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md
It was really annoying going `ctrl + f` so just added hyperlinks to the table of content. Also some of the headers needed an extra # to match with the hierarchy of current ToC.
=> DB_410c: Added hyperlinks to ToC in HardwareUserManual.md

ConsumerEdition/Bubblegum-96/Installation/README.md, ConsumerEdition/HiKey/GettingStarted/README.md, ConsumerEdition/MediaTekX20/GettingStarted/README.md, ConsumerEdition/MediaTekX20Pro/GettingStarted/README.md, mezzanine/README.md, mezzanine/aerocore2/README.md, mezzanine/audio-mezzanine/README.md, mezzanine/d3camera/README.md, mezzanine/ethernetcard/README.md, mezzanine/linkspritesensorkit/README.md, mezzanine/mipiadapter/README.md, mezzanine/neonkey/README.md, mezzanine/sensors-mezzanine/README.md, mezzanine/stm32/README.md, mezzanine/uartserial/README.md
Paths now represent what is currently the path for mezzanine boards
With the inclusion of #145
=> Fixed all mezzanine paths

ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Images_Wiki/README.md, ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/README.md, ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md, ConsumerEdition/imx7-96/getting-started/README.md, ConsumerEdition/imx7-96/guides/README.md, ConsumerEdition/imx7-96/hardware-docs/README.md, ConsumerEdition/imx7-96/hardware-docs/hardware-user-manual.md, ConsumerEdition/imx7-96/installation/README.md, ConsumerEdition/imx7-96/installation/board-recovery.md, ConsumerEdition/imx7-96/support/README.md
Fixes for a couple of 404's being raised by the custom link checker currently in place on the Bamboo CI builds for 96boards.org
@shovanuk
=> 404 fixes for 96boards Documentation

ConsumerEdition/DragonBoard-410c/BuildSource/README.md, ConsumerEdition/DragonBoard-410c/BuildSource/open_embedded.md, ConsumerEdition/HiKey/BuildSource/README.md, ConsumerEdition/HiKey/BuildSource/open_embedded.md, ConsumerEdition/guides/open_embedded.md
This commit modifies the existing OE guides such that a generic guide
will cover the board agnostic instructions and the board specific
guides will cover the flashing part.
=> oe: modify guides for DB410c and HiKey

ConsumerEdition/DragonBoard-410c/Guides/EnableSPI.md, ConsumerEdition/guides/mraa/gpio/README.md, ConsumerEdition/guides/mraa/i2c/README.md, ConsumerEdition/guides/mraa/led/README.md, ConsumerEdition/guides/mraa/uart/README.md
Restructure the EnableSPI guide with latest build info
Changes:
1. Specified latest build
2. Removed instruction for using custom boot image with device tree changes as it seems to be not needed.
2. Used spidev_test utility in kernel
3. Reduced SPIDEV max frequency to 500KHz as reported by the utility.
Fixes #187
=> Dragonboard410c: Guides: Modify EnableSPI guide

ConsumerEdition/DragonBoard-410c/Guides/enable-dmic.md
Add instructions for enabling and testing the DMIC in Dragonboard410c
using Arrow Audio Mezzanine
=> Dragonboard410c: Guides: Add DMIC guide

ConsumerEdition/DragonBoard-410c/Downloads/README.md
Link added for third part instructions. This link should be
changed to Fedora Wiki once the 96Boards section becomes
available.
=> ce/db410c/downloads: Added link to Fedora build and install

ConsumerEdition/guides/mraa/gpio/README.md, ConsumerEdition/guides/mraa/i2c/README.md, ConsumerEdition/guides/mraa/led/README.md, ConsumerEdition/guides/mraa/uart/README.md
Removed README.md.html extensions from all README
markdowns.
=> ce/guides/mraa: Fixed permalinks

EnterpriseEdition/Poplar/BuildSource/README.md, EnterpriseEdition/Poplar/GettingStarted/README.md, EnterpriseEdition/Poplar/Support/README.md
We plan to kill 'latest' branch and use 'master' instead, as
poplar-tools is the 'upstream' repository, and 'master' should be the
most idiomatic one to use.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
=> Poplar: use 'master' branch instead of 'latest' for poplar-tools

EnterpriseEdition/Poplar/BuildSource/README.md, EnterpriseEdition/Poplar/GettingStarted/README.md, EnterpriseEdition/Poplar/Support/README.md
The poplar-tools repository gets moved to 96boards-poplar, and
build_instructions.md is moved into Documentation repository.  Update
the URLs accordingly.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
=> Poplar: update tool and document repository URL

ConsumerEdition/dragonboard820c/README.md, ConsumerEdition/guides/mraa/README.md, EnterpriseEdition/Poplar/GettingStarted/README.md, EnterpriseEdition/Poplar/Guides/README.md, EnterpriseEdition/Poplar/Support/README.md
Fixes for broken links:
* Updated broken links on mraa guides page.
*  Updated broken links to recovery.md Poplar file
@shovanuk @sdrobertw
=> Broken links in Documentation

ConsumerEdition/B2260/Downloads/Debian.md, ConsumerEdition/dragonboard820c/README.md, ConsumerEdition/dragonboard820c/downloads/README.md, ConsumerEdition/dragonboard820c/getting-started/README.md, ConsumerEdition/dragonboard820c/guides/README.md, ConsumerEdition/dragonboard820c/hardware-docs/README.md, ConsumerEdition/dragonboard820c/installation/README.md, ConsumerEdition/dragonboard820c/installation/board-recovery.md, ConsumerEdition/dragonboard820c/installation/linux-fastboot.md, ConsumerEdition/dragonboard820c/installation/linux-sd.md, ConsumerEdition/dragonboard820c/installation/mac-sd.md, ConsumerEdition/dragonboard820c/installation/windows-sd.md, ConsumerEdition/dragonboard820c/support/README.md, ConsumerEdition/dragonboard820c/vendor-docs/README.md, mezzanine/audio-mezzanine/Guides/beginner-guides/README.md
96boards is failing to build due to some pages being referenced through the breadcrumb that don't have front matter. This should let 96boards builds go through providing no other broken links surface after merging this PR.
@shovanuk
=> Added front matter to pages causing broken links ~ removed anchor from broken links.

consumer/dragonboard410c/downloads/README.md
When browsing via github these links are not followed correctly.
=> Fix casing for the links

consumer/dragonboard820c/getting-started/README.md, iot/carbon/hardware-docs/README.md
Fixed DragonBoard820c Getting Started broken images and removed redirect that would cause a problematic loop.
@sdrobertw @shovanuk
=> Fixed DragonBoard820c Getting Started broken images / redirect loop fix

consumer/dragonboard410c/build/kernel.md
1. Install toolchain for cross-compiling
2. Retrieve kernel source
3. Build kernel/dtb/modules
4. Generate and flash boot image
5. Install modules
=> dragonboard: 410c: build: Add kernel build documentation

consumer/guides/zram_swapspace.md
The builds were moved from 96boards.org to linaro.org
=> Update links to builds

consumer/dragonboard820c/downloads/README.md
The text here is just a copy 'n paste from DB410C and risks misleading people (for examples see: http://discuss.96boards.org/t/820c-android-support/4094/2 ).
=> db820c: unlikely to ship with Android by default

consumer/dragonboard820c/installation/linux-fastboot.md
Removed the outdated links to images and simplified the installation instructions.
Note: I have left the OE section untouched. Once we merge the 820c support into existing OE doc, we can remove this.
=> dragonboard820c: installation: fastboot: Simplify installation instructions

consumer/dragonboard410c/build/open-embedded.md, consumer/dragonboard410c/downloads/android.md, consumer/dragonboard410c/downloads/debian.md, consumer/dragonboard410c/downloads/open-embedded.md, consumer/dragonboard410c/installation/board-recovery.md
The rescue images have just migrated to releases.linaro.org. Let's track them.
=> db410c: Update the rescue links

consumer/dragonboard820c/build/linux-kernel.md
With bootloaders #28 and beyond, the default rootfs device is /dev/sda7 (e.g. partition 'rootfs')
=> fix default rootfs

consumer/dragonboard820c/installation/linux-fastboot.md
Since bootloader #28 (and beyond) the GPT scheme defaults to a sinlge partition called 'rootfs' (no more  userdata).
also updated the OE version, rocko is the current branch.
=> Update default partition for rootfs

consumer/dragonboard820c/installation/board-recovery.md
Some boards have been returned and damaged, and initial investigation shows that it can be related to how S1 switch is setup. We need to make sure that the board is not powered and that no USB cable are plugged. Improve the documentation in this area.
=> Improve EDL mode instructions

consumer/dragonboard410c/installation/linux-fastboot.md
The fastboot steps in Step 3 (fastboot devices) and Step 4 (./flashall) did not indicate sudo use. All of the remaining fastboot commands do indicate using sudo, so I think these should also (they do not work otherwise for a normal user).
=> update linux-fastboot.md w/ add'tl sudo commands

consumer/imx7-96/README.md, consumer/imx7-96/additional-docs/README.md, consumer/imx7-96/downloads/README.md, consumer/imx7-96/getting-started/README.md, consumer/imx7-96/guides/README.md, consumer/imx7-96/guides/software-guide.md, consumer/imx7-96/guides/user-guide.md, consumer/imx7-96/hardware-docs/README.md, consumer/imx7-96/installation/README.md, consumer/imx7-96/support/README.md
- Added README.md with basic image template information
- Attempt to fix imx7-96 links throughout the section
- There seemed to be inaccurate redirects in place that were causing the build errors
=> consumer/imx7-96: Added README to additional-docs and fixed broken links

consumer/mediatekx20/downloads/third-party/aosp/linux-fastboot.md, consumer/mediatekx20/downloads/third-party/aosp/windows-fastboot.md, consumer/mediatekx20/installation/board-recovery.md
Since there is no support for flashing GPT partition on this platform,
lets remove the instructions for it.
Fixes #188
=> mediatekx20: Remove instructions for flashing GPT

CONTRIBUTE.md
…d is deprecated and we are now adding redirect rules to the routingrules.json file in the 96boards/website/_data folder
=> Removed the redirect_from from the CONTRIBUTE.md document

consumer/dragonboard820c/build/linux-kernel.md
Now that 820c support was merged in the 4.14 branch, we can get rid of the previously used temporary branch.
=> Update kernel build instructions

consumer/hikey/installation/board-recovery.md
Hikey recovery guide is outdated with new images and process. Hence update it
accordingly.
Fixes: #359 
=> hikey: recovery: Update instructions based on new images

consumer/hikey/build/README.md, consumer/hikey/build/linux-kernel.md
This commit adds guide for building linux kernel from source
for Hikey. It utilizes the debian package system for quickly
building and updating the kernel.
=> hikey: Add guide for building linux kernel from source

enterprise/poplar/hardware-docs/hw-user-manual.md
The table describing boot select jumpers messed up the value between
BOOTSEL0 and BOOTSEL2.  Fix it.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
=> ee: poplar: fix BOOTSEL jumpers description

consumer/dragonboard410c/build/README.md, consumer/dragonboard410c/build/kernel.md
This guide is missing the html rendering and also the entry in
top level README.md. Hence add these for better visibility in website.
=> dragonboard410c: Add html rendering for kernel building guide

consumer/dragonboard820c/build/linux-kernel.md
when we switch to full kernel build as Debian package, we changed the version string to be qcomlt-ARCH, we need to update the instructions accordingly.
=> update KERNELVERSION string

consumer/dragonboard410c/guides/enable-dmic.md
=> db410c: guides: dmic: Add missing mux reset command for CIC1

consumer/dragonboard820c/downloads/open-embedded.md, consumer/dragonboard820c/hardware-docs/README.md
I've found the replacements for the 820c snapshots broken links and updated.
=> Broken 820c snapshots image links fixed.

consumer/dragonboard410c/build/kernel.md
Command substitution should be $ARCH instead of $(ARCH) while using it
in command line.
=> db410c: build: Remove parantheses in command substitution

consumer/guides/tensorflow-installation.md
- The current TensorFlow require Bazel >= 0.10.0.
- The steps to modify the Bazel source file to be compatible with aarch64 was changed.
=> Update Bazel version and the turorial url to modify to aarch64

consumer/hikey/build/linux-kernel.md
=> hikey: build: Add instructions to override default device tree in GRUB

consumer/dragonboard410c/guides/pmic-pwm.md
Add a guide for using on-board PMIC PWM on Dragonboard410c running
debian.
=> db410c: guides: Add PMIC PWM on Dragonboard410c

CONTRIBUTE.md
Original text can do nothing but discourage people from submitting small typo fixes by weighing them down with pointless process. No one should require approval to send a PR. The only reason to pre-discuss is to avoid having to NACK PRs that are out of scope or where material is added in the wrong place. New text covers this case nicely.
Signed-of-by: Daniel Thompson <daniel.thompson@linaro.org>
=> CONTRIBUTE: No approval needed to send a PR

enterprise/developerbox/build/README.md
EDK2 recently made OpenSSL a sub-module. Updating the clone to use this feature should help avoid version skew problems in the future.
=> developerbox: build: Improve cloning of OpenSSL

enterprise/poplar-hoperun/README.md, enterprise/poplar-hoperun/hardware-docs/README.md, enterprise/poplar-hoperun/support/README.md
It updates following links for Hoperun Poplar board:
- product link on 96boards website
- poplar link on hoperun website
- download link of schematic
Signed-off-by: Jianguo Sun <sun_jianguo@hoperun.com>
=> ee: poplar-hoperun: update links for hoperun poplar board

consumer/dragonboard410c/guides/enable-spi.md
Currently the instructions to enable spidev are long, complex
and require the user to transfer huge quantities of data over the
network. Fix this by use the dt-update tools to update the DT.
=> db410c: enable-spi: Switch over to dt-update

enterprise/poplar-hoperun/hardware-docs/hw-user-manual.md, enterprise/poplar/hardware-docs/hw-user-manual.md
It fixes a typo in description of video and image encoding of Poplar board.
Signed-off-by: Jianguo Sun <sun_jianguo@hoperun.com>
=> ee: fix a typo in description of video and image encoding of Poplar board

consumer/dragonboard410c/guides/enable-ls-i2s.md
=> db410c: guides: Add Enabling LS-I2S on Dragonboard410c guide

enterprise/developerbox/hardware-docs/README.md
In order to use the 4 DIMM slots, registered DIMMs are required.
For example, using the Crucial UDIMM CT4G4DFS824A,
you will be limited to 2 DIMM slots.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
=> developerbox: clarify RAM limitation

enterprise/developerbox/hardware-docs/README.md
This DIMM is not working stably. Kernel compilation fails, memtester
outputs some errors. Remove it from the verified list.
Fixes: #488
=> developerbox: hardware-docs: Remove TS2GHR72V4B

consumer/dragonboard820c/installation/build-linux-host.md
QDL is the tool to rescue the board or flash images into the onboard storage, it has nothing to do with preparing a Linux Host for DB820c.
=> Remove references to QDL

consumer/dragonboard820c/installation/linux-fastboot.md
Instead of duplicating the reference to the USB flashing tools, add links between the pages.
=> DB820c: improve install instructions

consumer/dragonboard820c/installation/board-recovery.md
If ModemManager is running, it will interfere with the flashing.
Add a note about this, and suggest how the user can disable it.
Signed-off-by: Niklas Cassel <niklas.cassel@linaro.org>
=> db820c: board-recovery: add note about ModemManager interfering with qdl

enterprise/developerbox/installation/centos.md, enterprise/developerbox/installation/rhel.md
Currently these instructions are complex and the RHEL one is full of
weasel words about graphics that, after more extensive testing, turns
out to be a bit too conservative.
Fix this by simplifying the instructions and encouraging use of
graphics.
=> developerbox: install: Simplify CentOS and RHEL install guide

enterprise/developerbox/installation/centos.md, enterprise/developerbox/installation/rhel.md
Currently the table of contents is out-of-date w.r.t. the actual
content. Fix this.
=> developerbox: install: Fix table of contents

consumer/dragonboard410c/installation/board-recovery.md, consumer/dragonboard820c/installation/board-recovery.md, consumer/guides/qdl.md
QDL is a flashing tool used for any QCOM SoC, it's not specific
DB820c (it's not even specific to Dragonboard, but any QC hardware),
so let's create a generic guide and link there instead.
Also:
* add USB flashing instructions for 410c, which were missing
* improve the QDL doc/wording
=> dragonboard: move qdl info in its own document

iot/bpi96/README.md
Github doesn't support colored text, the website _should_ render it
=> bpi96: big red warning about 3.3v

consumer/README.md, consumer/dragonboard-family/README.md, consumer/hikey-family/README.md
This commit contains changes to the README.md index pages.
Device folders and guides remain where the were.
- Added dragonboard-family folder with README.md
- Added hikey-family folder with README.md
=> common dragonboard and hikey documentation: index

consumer/dragonboard/dragonboard410c/build/kernel.md, consumer/dragonboard/dragonboard820c/build/linux-kernel.md
This PR modifies the kernel build instructions for Dragonboard family to accomodate
a section to add build dependencies on debian based systems and one minor wording
change.
=> consumer: Modify kernel build instructions

consumer/dragonboard/dragonboard410c/guides/enable-spi.md
The instructions for using the spidev_test utility was wrong. Fix it with
correct instructions.
=> db410c: guides: enable-spi: Modify instructions for spidev_test utility

consumer/README.md
For the board families sections, it makes sense to explicitly mention
Rock960c instead of "Board based on Rockchip RK3399".
=> consumer: Specify Rock960c explicitly

consumer/guides/open_embedded.md
For OE, since we support sumo in our oe-rpb-manifest it makes sense to
switch to sumo which is also the latest stable version of OpenEmbedded.
=> consumer: guides: OE: Switch to sumo version

consumer/rock/downloads/debian.md, consumer/rock/downloads/ubuntu.md
Add default username and password on the download page for Ubuntu/Debian
image since some users ignore the readme in the image tar ball.
Fixes: #556
Signed-off-by: Jack Ma <jack@vamrs.com>
=> consumer: rock: add note for image download

consumer/hikey/hikey960/getting-started/README.md, consumer/hikey/hikey960/hardware-docs/hardware-user-manual.md
The recent grand renaming left many of the image links in the hikey960 doc
broken. Fix them.
=> hikey960: Fix broken images

consumer/hikey/hikey970/installation/board-recovery.md
Since there are two Type-C ports available on board, explicitly specify the
location of Recovery Type-C port for clarification.
Fixes: #574
=> hikey: hikey970: Modify recovery instructions to use correct Type-C port

consumer/dragonboard/dragonboard410c/installation/linux-fastboot.md
Add instructions for unzipping the downloaded boot/rootfs files for Debian and
Android.
Fixes: #594
=> db410c: installation: fastboot: Add instructions for unzipping files

consumer/rock/build/README.md, consumer/rock/build/linux-kernel.md
Add build guide for Linux kernel on Rock960.
=> rock960: Add build guide for Linux kernel

consumer/hikey/hikey960/downloads/debian.md
As discussed on the forum currently the documentation does a poor
job of communicating the current status of Debian for Hikey960. This
page describes an unreleased skunkworks project that does not
support graphics out-of-the-box (which many users will expect) and
we need to make this clear through something much more obvious than
the server the files are downloaded from!
Additional, since this is one of the few bits of software for 96Boards
which requires a UART we also add a warning about checking the
UART adapter is suitable before connecting it.
Reported-by: Torbjörn Granlund
Link: https://discuss.96boards.org/t/6310
Fixes: #619
=> hikey960: debian: Warn that this is unreleased snapshot

consumer/hikey/hikey960/installation/linux-fastboot.md
Currently the Debian for Hikey960 images do not support HDMI out-of-the-box. Suggesting connection of mouse, keyboard and monitor is thus rather pointless! Change this.
Reported-by: Torbjörn Granlund
=> hkey960: install: No HDMI for Debian

consumer/hikey/README.md, consumer/hikey/hikey970/build/aosp.md, consumer/hikey/hikey970/build/linux-kernel.md
- Removed mention of "Common Hikey Guides" as they don't exist
- fixes #624
- Added link to kernel build guide for AOSP build guide
- fixes #621
=> fixes: couple of fixes for hikey and hk970

consumer/rock/rock960c/getting-started/README.md
Attempt to fix images in getting started sections
for website rendering.
=> consumer/rock/rock960c: Fix images in getting-started

consumer/rock/rock960/hardware-docs/hardware-user-manual.md
Add Booting Linux Kernel using U-Boot guide for HiKey board.
=> hikey: guides: Add Booting Linux Kernel using U-Boot guide

consumer/hikey/hikey970/installation/board-recovery.md
Prefixing user commands with $ adds little in the way of readability but makes
copy and paste difficult.
Add some extra dependencies that are not currently listed.
=> hikey970: Remove copy-n-paste defeat devices and update dependencies

consumer/sophon-edge/build/README.md
=> consumer/sophon-edge: Added links to build instructions

consumer/hikey/hikey960/README.md, consumer/hikey/hikey960/guides/README.md, consumer/hikey/hikey960/guides/openCL-support.md
This guide provides steps for installing Mali G71 drivers and enable
openCL support on Debian/HiKey960.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> hikey960: debian: Add guide to enable openCL support

consumer/hikey/hikey960/guides/openCL-support.md
Rather than using insmod, use depmod and modprobe utilities to enable
auto-loading of GPU kernel driver during boot.
Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
=> hikey960: openCL: Update for GPU kernel driver auto-loading

consumer/dragonboard/dragonboard410c/downloads/debian.md, consumer/dragonboard/dragonboard410c/downloads/open-embedded.md, consumer/rock/downloads/ubuntu.md
The following links are fixed:
/documentation/consumer/dragonboard/dragonboard410c/downloads/debian.md.html:
http://releases.linaro.org/96boards/dragonboard410c/linaro/rescue/latest/dragonboard410c_bootloader_emmc_linux-*.zip [404]
/documentation/consumer/dragonboard/dragonboard410c/downloads/open-embedded.md.html:
http://releases.linaro.org/96boards/dragonboard410c/linaro/rescue/latest/dragonboard410c_bootloader_emmc_linux-*.zip [404]
/documentation/consumer/rock/downloads/ubuntu.md.html:
https://dl.vamrs.com/products/rock960c/images/ubuntu/ubuntu_server_16.04_arm64_rootfs_20171108.img.gz [404]
=> link fixes

consumer/dragonboard/dragonboard410c/installation/board-recovery.md
During board recovery, the use of debug UART is completely optional.
So, let's make it clear in the recovery instructions and try to make
use of the logs from the tool for monitoring the progress.
Fixes: #603
=> consumer: db410c: Clarify the use of debug UART during recovery

consumer/dragonboard/dragonboard820c/installation/board-recovery.md, consumer/hikey/hikey960/installation/board-recovery.md, consumer/hikey/hikey970/installation/board-recovery.md
Debug UART is not necessary when recovering a CE board. Also, the
current recovery instructions doesn't make use of debug console output
for monitoring the recovery process. Hence, remove the references to
debug UART from recovery instructions and use `ttyUSB0` as the recovery
port.
=> consumer: Remove the use of debug UART during recovery

consumer/hikey/hikey620/build/linux-kernel.md
We have switched to a new kernel tree for the latest debian release. Hence,
use the same in the kernel build guide.
=> consumer: hikey: Use updated kernel tree

enterprise/developerbox/guides/README.md, enterprise/developerbox/guides/uefi-guide.md
This pull request is adding uefi boot menu introduction.
Some Developerbox customers send queries how to use uefi boot menu,
this document will help customer as a reference to the uefi.
Signed-off-by: Masahisa Kojima <masahisa.kojima@linaro.org>
=> developerbox: guides: Add uefi guide to introduce uefi use cases

consumer/rock/installation/linux-mac-rkdeveloptool.md
Since the `rkdeveloptool` can fail at the first instruction itself,
it makese sense to mention the link to the Troubleshooting section there
itself. While adding the link, let's also include the commonly encountered
error message.
Fixes: #748
=> rock960: installation: Link to Troubleshooting section

iot/wistrio/installation/README.md, iot/wistrio/installation/linux.md, iot/wistrio/installation/windows.md
Add installation instructions for Linux host and split the Windows instructions.
=> wistrio: Add installation instructions for Linux host

consumer/guides/multi-usb-camera.md
Account for the 80% bandwidth limit for isochronous transfers in the initial bandwidth estimation.
Rephrase a couple of bullet points so the paragraph introducing the bandwidth FAQ can commence with "Although" (which makes it easy to find when scan reading).
Fix the auto-linkification for the UVC FAQ.
=> guides/usb-camera: Minor rephrasing and link fixing

consumer/dragonboard/dragonboard820c/installation/board-recovery.md
Fix dead link to recovery binaries. It now points at the
directory so the link should always be valid rather than
relying on the build number.
Also include section about ensuring we use the latest qdl
tool which has a 3 second delay, added in
https://git.linaro.org/landing-teams/working/qualcomm/
qdl.git/commit/?id=7623ff5e1ece613ba886c9a0b2767c2dd797f725
This is required to use the qdl tool with the 820c board.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> consume: dragonboard820c: update recovery documentation

consumer/dragonboard/dragonboard410c/build/kernel.md
Download toolchain link is broken. At linaro toolchain site as of now I can see GCC 7 is from Linaro and GCC 8 points to ARM. so I suggest to take gcc 7 link from Linaro site.
=> Broken gcc toolchain link fix

consumer/dragonboard/dragonboard410c/guides/DragonBoard-Qt-Setup.md, consumer/dragonboard/dragonboard845c/installation/README.md, consumer/rock/downloads/debian.md
- rock960 downloads table fix. fixes #794
- db845: fix installation page mentioning 410c instead of 845. fixes #789
- db410c: QT5 installation link fixes. fixes #717
=> documentation fixes

consumer/guides/qdl.md
The build also depends on libudev-dev without which the compiler would return following error.
qdl.c:43:10: fatal error: libudev.h: No such file or directory
#include <libudev.h>
=> Update qdl.md to include libudev dependancy

consumer/guides/debian.md
This is an initial write up that shows how Linaro Debian builds are
typically generated, using Qualcomm Dragonboard CI jobs.
=> Documentation the process of building Debian images using Linaro CI.

consumer/dragonboard/dragonboard845c/installation/board-recovery.md
add a better description regarding the button use to put the board in USB flashing mode.
=> db845c: board-recovery: add button name

consumer/hikey/hikey620/downloads/debian.md, consumer/hikey/hikey620/installation/board-recovery.md, consumer/hikey/hikey620/installation/linux-fastboot.md, consumer/hikey/hikey960/downloads/debian.md, consumer/hikey/hikey960/installation/board-recovery.md
Latest UEFI binaries were moved to `https://snapshots.linaro.org/reference-platform/components/uefi-staging/latest/`. Hence fix those in docs and also fix couple of references to `builds.96boards.org`.
=> hikey: Fix links to latest UEFI binaries

consumer/dragonboard/dragonboard410c/installation/board-recovery.md
Some bootloader packages have rawprogram.xml and patch.xml, some have rawprogram0.xml and patch0.xml. With this change the instructions would work in both cases.
=> db410c: update qdl instructions

consumer/dragonboard/dragonboard410c/README.md, consumer/dragonboard/guides/contribute/README.md
Moving the DragonBoard410c contribute guide to the generic DragonBoard guides folder
- redirects added using the jekyll_redirect_from plugin have been moved to the routingrules.json file in the [website repo](https://github.com/96boards/website)
- the new structure used - folder containing a `README.md` file to avoid using .md.html permalinks
=> Moving the DragonBoard410c contribute guide to the generic DragonBoard guides folder

mezzanine/on-camera/README.md, mezzanine/on-camera/guides/README.md
The guides for the on-camera mezzanine are not "Coming Soon". There
are no confirmed plans to write any guides for this board so remove
the misleading placeholder.
Fixes: #803
=> mezzanine: on-camera: Remove Useful Guides

consumer/ultra96/ultra96-v2/downloads/linux.md
There is no v2 image hosted on our builds, hence linking the the one
available on Avnet's site in meantime.
=> Fix link to ultra96-v2 image

consumer/dragonboard/dragonboard845c/installation/board-recovery.md
Provide some extra details on how to manually force fastboot
mode, as some users saw the system entering usb-crash mode
instead after qdl flashing.
Signed-off-by: John Stultz <john.stultz@linaro.org>
=> Update doc to detail how to manually enter fastboot mode

consumer/dragonboard/dragonboard845c/downloads/debian.md, consumer/dragonboard/dragonboard845c/downloads/open-embedded.md
Now that a release exist, point to it instead of (unstable) snapshots.
Signed-off-by: Loic Poulain <loic.poulain@linaro.org>
=> Dragonboard845c: downloads: Debian/OE: Point to release

consumer/ultra96/ultra96-v2/getting-started/README.md
This PR replaces my previous, #858, and updates the documentation to reflect the ultra96v2 as received. I'm closing the previous in favor or this.
Original PR text:
The current getting started documentation for the Ultra96v2 is not correct. I updated it for the v2 board revision (new LED arrangement) and the current distributed package (blank SD card). This should address #855 that I reported.
=> Updated documentation to reflct ultra96-v2 as shipped

enterprise/developerbox/build/README.md
OSS SCP-firmware only supports SCMI, need additional information
to build the Trusted Firmware with SCMI enabled.
In addition, SynQuacer platform is merged into Trusted Firmware-A
repository, plat build option must be "synquacer".
Signed-off-by: Masahisa Kojima <masahisa.kojima@linaro.org>
=> developerbox: update Trusted Firmware-A build step

consumer/hikey/hikey620/downloads/debian.md
Fixing broken links to ptable-4g and ptable 8g. New location is: http://releases.linaro.org/96boards/hikey/linaro/debian/latest/
=> Update ptable locations in debian.md

consumer/rock/installation/linux-mac-rkdeveloptool-android.md, consumer/ultra96/ultra96-v2/hardware-docs/README.md, enterprise/akebi96/getting-started/README.md, enterprise/akebi96/support/README.md
- akebi96: multiple links and typos fixed
- rock: add missing dependency. fixes: #873
- ultra96v2: fixed hw user manual link. fixes: #881
=> link and typo fixes

consumer/dragonboard/dragonboard845c/installation/board-recovery.md
We have regular builds published, but we also make releases every few months. Users should by default install the most recent release, not the most recent builds.
=> db845c: recommend official releases for bootloader

iot/orangepi-i96/downloads/README.md
Updated the 404 Links for the Debian,Ubuntu.
Added the Android Image Download Page.
Removed Android SD Card, and Android NAND as those are Now merged into one Android Link leading to the files.
Removed Raspbian Download as its not present on the Orange Pi Website anymore.  
Signed of by Thore Krug: opensource[at]thorekrug.de
=> Fix of 404 links

consumer/dragonboard/dragonboard410c/guides/fedora.md, consumer/dragonboard/dragonboard410c/guides/force-display-res.md, consumer/dragonboard/dragonboard820c/installation/linux-fastboot.md, consumer/dragonboard/dragonboard845c/downloads/debian.md, consumer/dragonboard/dragonboard845c/downloads/open-embedded.md, consumer/hikey/hikey620/downloads/aosp.md, consumer/sophon-edge/guides/sd_boot_guide.md, consumer/ultra96/ultra96-v1/hardware-docs/README.md, consumer/ultra96/ultra96-v1/hardware-docs/hw-user-manual.md, consumer/ultra96/ultra96-v2/hardware-docs/README.md, consumer/ultra96/ultra96-v2/hardware-docs/hw-user-manual.md, enterprise/cello/quickstart/README.md, enterprise/developerbox/getting-started/README.md, iot/orangepi-i96/build/README.md, iot/orangepi-i96/getting-started/README.md, iot/wistrio/downloads/README.md, mezzanine/stm32/README.md
TODO:
- https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/latest/ :
- needs fix on the file server side as latest folder is missing and that should not be the case
=> fix broken links in documentation repo

consumer/dragonboard/dragonboard845c/downloads/debian.md, consumer/dragonboard/dragonboard845c/downloads/open-embedded.md
Wrong name was used in download pages for OE and Debian.
=> consumer: db845c: fix typos

consumer/dragonboard/qualcomm-robotics-rb5/installation/board-recovery.md
Use the 'latest' release, which is always recommended.
=> dragonboard: rb5: fix download link

enterprise/developerbox/installation/board-recovery.md
The correct BOOT_CTL register address of the DeveloperBox is 0x48100000, and "auto0.tap" must be a parameter of "target" command.
=> developerbox: Fix BOOT_CTL address and typo

consumer/dragonboard/qualcomm-robotics-rb5/downloads/debian.md, consumer/dragonboard/qualcomm-robotics-rb5/downloads/open-embedded.md
Use 'latest' link instead of fixed (old) release.
=> rb5: fix link to latest bootloader release

enterprise/developerbox/build/README.md
The latest SCP firmware cannot be built using the Makefile.
I was able to build it using Makefile.cmake instead, so I changed it.
=> Fix SCP firmware build command

enterprise/developerbox/build/README.md
DO_X86EMU is replaced with X64EMU_ENABLE, let's fix the
build procedure.
Signed-off-by: Masahisa Kojima <masahisa.kojima@linaro.org>
=> developerbox: fix EDK2 build option
